name: Autoupdate Readme

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: pip install -r requirements.pip
    - name: Auto update
      run: |
        echo "GH_TOKEN: $GH_TOKEN"  # Print the token to verify
        python main.py
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - uses: stefanzweifel/git-auto-commit-action@v5
      id: auto-commit-action #mandatory for the output to show up in ${{ steps }}
      with:
        commit_message: "Auto update README.md"
